/* Generated By:JavaCC: Do not edit this line. PseintConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PseintConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 1;
  /** RegularExpression Id. */
  int FIN = 2;
  /** RegularExpression Id. */
  int ENTERO = 3;
  /** RegularExpression Id. */
  int FLOTANTE = 4;
  /** RegularExpression Id. */
  int CADENA = 5;
  /** RegularExpression Id. */
  int CARACTER = 6;
  /** RegularExpression Id. */
  int BOOLEANO = 7;
  /** RegularExpression Id. */
  int LETRA = 8;
  /** RegularExpression Id. */
  int NUMERO = 9;
  /** RegularExpression Id. */
  int CADENA_TEXTO = 10;
  /** RegularExpression Id. */
  int CARACTER_TEXTO = 11;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 12;
  /** RegularExpression Id. */
  int NUMERO_DECIMAL = 13;
  /** RegularExpression Id. */
  int BOOLEANO_FALSO = 14;
  /** RegularExpression Id. */
  int BOOLEANO_VERDADERO = 15;
  /** RegularExpression Id. */
  int COMENTARIO = 16;
  /** RegularExpression Id. */
  int DELIMITADOR = 17;
  /** RegularExpression Id. */
  int LEER = 18;
  /** RegularExpression Id. */
  int ESCRIBIR = 19;
  /** RegularExpression Id. */
  int DEFINIR = 20;
  /** RegularExpression Id. */
  int COMO = 21;
  /** RegularExpression Id. */
  int ASIGNACION = 22;
  /** RegularExpression Id. */
  int SUMA = 23;
  /** RegularExpression Id. */
  int RESTA = 24;
  /** RegularExpression Id. */
  int MULTIPLICACION = 25;
  /** RegularExpression Id. */
  int DIVISION = 26;
  /** RegularExpression Id. */
  int MODULO = 27;
  /** RegularExpression Id. */
  int LOGICO_AND = 28;
  /** RegularExpression Id. */
  int LOGICO_OR = 29;
  /** RegularExpression Id. */
  int LOGICO_NOT = 30;
  /** RegularExpression Id. */
  int ASIGNACION_COMPUESTA = 31;
  /** RegularExpression Id. */
  int OPERADOR_IGUAL = 32;
  /** RegularExpression Id. */
  int OPERADOR_DIFERENTE = 33;
  /** RegularExpression Id. */
  int OPERADOR_MAYOR = 34;
  /** RegularExpression Id. */
  int OPERADOR_MENOR = 35;
  /** RegularExpression Id. */
  int OPERADOR_MAYOR_IGUAL = 36;
  /** RegularExpression Id. */
  int OPERADOR_MENOR_IGUAL = 37;
  /** RegularExpression Id. */
  int OPERADOR_DOS_PUNTOS = 38;
  /** RegularExpression Id. */
  int PAREN_ABIERTO = 39;
  /** RegularExpression Id. */
  int PAREN_CERRADO = 40;
  /** RegularExpression Id. */
  int INICIO_CICLO_PARA = 41;
  /** RegularExpression Id. */
  int CONDICION_CICLO_PARA = 42;
  /** RegularExpression Id. */
  int INCREMENTO_CICLO_PARA = 43;
  /** RegularExpression Id. */
  int FIN_CICLO_PARA = 44;
  /** RegularExpression Id. */
  int INICIO_CICLO_MIENTRAS = 45;
  /** RegularExpression Id. */
  int FIN_CICLO_MIENTRAS = 46;
  /** RegularExpression Id. */
  int INICIO_CICLO_REPETIR = 47;
  /** RegularExpression Id. */
  int CONDICION_CICLO_REPETIR = 48;
  /** RegularExpression Id. */
  int INICIO_CONDICIONAL_SI = 49;
  /** RegularExpression Id. */
  int ENTONCES = 50;
  /** RegularExpression Id. */
  int CONDICIONAL_SINO = 51;
  /** RegularExpression Id. */
  int FIN_CONDICIONAL_SI = 52;
  /** RegularExpression Id. */
  int INICIO_CONDICIONAL_SEGUN = 53;
  /** RegularExpression Id. */
  int CASO = 54;
  /** RegularExpression Id. */
  int CASO_PREDETERMINADO = 55;
  /** RegularExpression Id. */
  int FIN_SEGUN = 56;
  /** RegularExpression Id. */
  int HACER = 57;
  /** RegularExpression Id. */
  int VARIABLE = 58;
  /** RegularExpression Id. */
  int NUMERO_INVALIDO = 63;
  /** RegularExpression Id. */
  int INVALIDO = 64;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Algoritmo\"",
    "\"FinAlgoritmo\"",
    "<ENTERO>",
    "<FLOTANTE>",
    "<CADENA>",
    "<CARACTER>",
    "<BOOLEANO>",
    "<LETRA>",
    "<NUMERO>",
    "<CADENA_TEXTO>",
    "<CARACTER_TEXTO>",
    "<NUMERO_ENTERO>",
    "<NUMERO_DECIMAL>",
    "\"Falso\"",
    "\"Verdadero\"",
    "<COMENTARIO>",
    "\";\"",
    "\"Leer\"",
    "\"Escribir\"",
    "\"Definir\"",
    "\"Como\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<ASIGNACION_COMPUESTA>",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"Para\"",
    "\"Hasta que\"",
    "\"Con incremento\"",
    "\"FinPara\"",
    "\"Mientras\"",
    "\"FinMientras\"",
    "\"Repetir\"",
    "\"Finaliza cuando\"",
    "\"Si\"",
    "\"Entonces\"",
    "\"Sino\"",
    "\"FinSi\"",
    "\"Segun\"",
    "\"Caso\"",
    "\"En otro caso\"",
    "\"FinSegun\"",
    "\"Hacer\"",
    "<VARIABLE>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "<NUMERO_INVALIDO>",
    "<INVALIDO>",
  };

}
