/* Generated By:JavaCC: Do not edit this line. PseasyTokenManager.java */
package src;
import java.util.ArrayList;
import src.TablaIdentificadores;
import src.ArchivoCodigoIntermedio;
import src.GeneradorCodigo;

/** Token Manager. */
public class PseasyTokenManager implements PseasyConstants
{
    static ArrayList<String> tabla = new ArrayList();

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x10000000L) != 0L)
            return 10;
         if ((active0 & 0x3ffff00001cc0feL) != 0L)
         {
            jjmatchedKind = 58;
            return 13;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 8;
         if ((active0 & 0x7000000L) != 0L)
            return 7;
         if ((active0 & 0xc00000L) != 0L)
            return 27;
         return -1;
      case 1:
         if ((active0 & 0x3f5ff00001cc0feL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return 13;
         }
         if ((active0 & 0xa000000000000L) != 0L)
            return 13;
         if ((active0 & 0x18000000L) != 0L)
            return 7;
         return -1;
      case 2:
         if ((active0 & 0x37dff00001cc0feL) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 2;
            return 13;
         }
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 3:
         if ((active0 & 0x335fe000018c0feL) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 3;
            return 13;
         }
         if ((active0 & 0x48010000040000L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 4:
         if ((active0 & 0x105fe00001880feL) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 4;
            return 13;
         }
         if ((active0 & 0x230000000004000L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x105fc00001880d6L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 5;
            return 13;
         }
         if ((active0 & 0x28L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x900000100000L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x1056c00000880d6L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 6;
            return 13;
         }
         return -1;
      case 7:
         if ((active0 & 0x14c0000008006L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 7;
            return 13;
         }
         if ((active0 & 0x1042000000800d0L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x4c0000000004L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 8;
            return 13;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8002L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0xc0000000000L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x400000000004L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 9;
            return 13;
         }
         return -1;
      case 10:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 10;
            return 13;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x400000000000L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x4L) != 0L)
            return 13;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 58;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 13:
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L);
      case 33:
         jjmatchedKind = 29;
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 37:
         return jjStartNfaWithStates_0(0, 26, 7);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 40:
         return jjStopAtPos(0, 38);
      case 41:
         return jjStopAtPos(0, 39);
      case 42:
         return jjStartNfaWithStates_0(0, 24, 7);
      case 43:
         return jjStartNfaWithStates_0(0, 22, 27);
      case 44:
         return jjStopAtPos(0, 17);
      case 45:
         return jjStartNfaWithStates_0(0, 23, 27);
      case 47:
         return jjStartNfaWithStates_0(0, 25, 7);
      case 58:
         return jjStopAtPos(0, 37);
      case 59:
         return jjStopAtPos(0, 16);
      case 60:
         jjmatchedKind = 34;
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 61:
         jjmatchedKind = 21;
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 62:
         jjmatchedKind = 33;
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x2L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40000000000060L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x80000100000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x84000000080008L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x111500000004014L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x200020000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x2a000000000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(1, 61);
         break;
      case 38:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 27, 7);
         break;
      case 61:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 31);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 35);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(1, 36);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x240030000004060L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x20880000148000L);
      case 73:
      case 105:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x119700000000004L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x12L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x84040000000008L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 124:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(1, 28, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000c0000080000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000040000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000002L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x119500000000004L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x90L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000008040L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x40020000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000008L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 13);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000044L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x200800000000028L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L);
      case 79:
      case 111:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 51, 13);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 54, 13);
         return jjMoveStringLiteralDfa4_0(active0, 0x84000000000002L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      case 82:
      case 114:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 13);
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000080000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x110000000004000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000010L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x120000008010L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000c0000000080L);
      case 73:
      case 105:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 52, 13);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000080000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000004L);
      case 78:
      case 110:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 53, 13);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000100020L);
      case 79:
      case 111:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 13);
         break;
      case 82:
      case 114:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 57, 13);
         return jjMoveStringLiteralDfa5_0(active0, 0xaL);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x80a00000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 65:
      case 97:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 5, 13);
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000004L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x1800000100002L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0xc0000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x10L);
      case 79:
      case 111:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(5, 3, 13);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x80300000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 44, 13);
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x40c0000008040L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000080L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000004L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      case 82:
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 13);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 47, 13);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x12L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000000L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000L);
      case 69:
      case 101:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(7, 4, 13);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x2L);
      case 78:
      case 110:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 56, 13);
         return jjMoveStringLiteralDfa8_0(active0, 0xc0000000000L);
      case 79:
      case 111:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 13);
         break;
      case 82:
      case 114:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(7, 6, 13);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 13);
         return jjMoveStringLiteralDfa8_0(active0, 0x8004L);
      case 83:
      case 115:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 45, 13);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 50, 13);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000000L);
      case 69:
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(8, 41);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x4L);
      case 79:
      case 111:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(8, 1, 13);
         else if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(8, 15, 13);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0xc0000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x80400000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000000L);
      case 79:
      case 111:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 42, 13);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 43, 13);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x4L);
      case 83:
      case 115:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 46, 13);
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000000000L);
      case 79:
      case 111:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(11, 2, 13);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(11, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(14, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 27;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0xac2000000000L & l) != 0L)
                     jjCheckNAdd(7);
                  else if (curChar == 35)
                     jjCheckNAddStates(5, 7);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 8;
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(4, 5);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(1, 2);
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(21, 22);
                  else if (curChar == 61)
                  {
                     if (kind > 30)
                        kind = 30;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAdd(20);
                  }
                  break;
               case 1:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if (curChar == 34 && kind > 10)
                     kind = 10;
                  break;
               case 3:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(4, 5);
                  break;
               case 4:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if (curChar == 39 && kind > 11)
                     kind = 11;
                  break;
               case 6:
                  if ((0xac2000000000L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if (curChar == 61 && kind > 30)
                     kind = 30;
                  break;
               case 8:
                  if (curChar == 38)
                     jjCheckNAdd(7);
                  break;
               case 9:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 14:
                  if (curChar == 35)
                     jjCheckNAddStates(5, 7);
                  break;
               case 15:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 16:
                  if ((0x2400L & l) != 0L && kind > 63)
                     kind = 63;
                  break;
               case 17:
                  if (curChar == 10 && kind > 63)
                     kind = 63;
                  break;
               case 18:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(20);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(21, 22);
                  break;
               case 22:
                  if (curChar == 46)
                     jjCheckNAdd(23);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(23);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddStates(0, 4);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 58)
                        kind = 58;
                     jjCheckNAdd(13);
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 1:
                  jjAddStates(8, 9);
                  break;
               case 4:
                  jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 10:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
               case 13:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(13);
                  break;
               case 15:
                  jjAddStates(5, 7);
                  break;
               case 26:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjstateSet[jjnewStateCnt++] = 26;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(8, 9);
                  break;
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 15:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(5, 7);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 27 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   20, 21, 22, 25, 26, 15, 16, 18, 1, 2, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, "\73", "\54", null, null, null, "\75", "\53", "\55", "\52", "\57", 
"\45", "\46\46", "\174\174", "\41", null, "\75\75", "\41\75", "\76", "\74", "\76\75", 
"\74\75", "\72", "\50", "\51", null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x7fffffffffffcffL, 0x0L, 
};
static final long[] jjtoSkip = {
   0xf800000000000000L, 0x3L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[27];
private final int[] jjstateSet = new int[54];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
/** Constructor. */
public PseasyTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public PseasyTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 27; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 65)
   {
      jjmatchedKind = 65;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         SkipLexicalActions(null);
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 64 :
         if (image == null)
            image = new StringBuffer();
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                  tabla.add("Lexical error at line:" + input_stream.getBeginLine() + " column:" + input_stream.getBeginColumn() +
                                                                     " invalid id:" + image);
         break;
      case 65 :
         if (image == null)
            image = new StringBuffer();
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      tabla.add("Lexical error at line:" + input_stream.getBeginLine() + " column:" + input_stream.getBeginColumn() +
                    "invalid token:" + image);
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
